inventory-api
├── manage.py
├── requirements.txt
├── README.md
└── inventory
    ├── __init__.py
    ├── settings.py
    ├── urls.py
    ├── wsgi.py
    ├── asgi.py
    └── api
        ├── __init__.py
        ├── admin.py
        ├── apps.py
        ├── models.py
        ├── serializers.py
        ├── urls.py
        ├── views.py
        └── tests.py